name: environment example
on:
  workflow_dispatch:
  push:
# on:
#   schedule:
#     - cron: "*/7 * * * *"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: |
          echo ENV: ${{ env.MESSAGE }}
          echo VARIABLE: ${{ vars.MESSAGE }}
          echo SECRET: ${{ secrets.APP_SECRET }}
