apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: harbor.prd.tps.com/library/action-cicd:771ebcfe5039e2e173e4c41d77593c91402b7c19
          ports:
            - containerPort: 80
