apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: harbor.prd.tps.com/library/action-cicd:9f671c483a897750f9f63a3cbb81483ec7c54959
          ports:
            - containerPort: 80
