apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: harbor.prd.tps.com/library/action-cicd:ad8c5e47608230568b413ffc646976b852e4fe04
          ports:
            - containerPort: 80
