helm:
  parameters:
  - name: image.name
    value: harbor.dev.trb.com/infra/nginx-image-updater-sample
    forcestring: true
  - name: image.tag
    value: 0.3.0
    forcestring: true
  - name: image.repository
    value: harbor.dev.trb.com/infra/nginx-image-updater
    forcestring: true
  - name: sample.image.repository
    value: harbor.dev.trb.com/infra/nginx-image-updater-sample
    forcestring: true
  - name: sample.image.tag
    value: "12345"
    forcestring: true
