helm:
  parameters:
  - name: image.name
    value: harbor.dev.trb.com/infra/nginx-image-updater-sample
    forcestring: true
  - name: image.tag
    value: 0.1.3
    forcestring: true
  - name: image.repository
    value: harbor.dev.trb.com/infra/nginx-image-updater
    forcestring: true
  - name: sample.image.repository
    value: harbor.dev.trb.com/infra/nginx-image-updater-sample
    forcestring: true
  - name: sample.image.tag
    value: 20250521-1740344
    forcestring: true
