name: remote ssh command
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Kaniko and build Docker image
      - name: Build and Push Docker Image using Kaniko
        uses: gcr.io/kaniko-project/executor:latest
        with:
          args: >
            --context . 
            --dockerfile ./Dockerfile 
            --destination ${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}
            --insecure
